language: node_js

before_script:
- npm install -g grunt-cli
- npm install -g bower
- bower install

after_success:
- npm install -g jscoverage
- jscoverage src src-cov
- grunt jasmine:app-cov | node_modules/jasmine-jscoverage-reporter/convert-to-coveralls.js | curl -F "json_file=@-" https://coveralls.io/api/v1/jobs
